#pragma once

#define LED_PIN 26
#define MATRIX_SIZE 16

#define MAC_ADDRESS "7C:9E:BD:E2:DF:32"

#define TICKSPEED 60
#define INPUTSPEED (TICKSPEED / 8)

#define TICKDELAY (1000000 / TICKSPEED)

#define PLAYFIELD_WIDTH 8
#define PLAYFIELD_HEIGHT 16

#define LEVELCOUNT_WIDTH 7
#define LEVELCOUNT_HEIGHT 3